version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: invoice_portal_postgres
    environment:
      POSTGRES_DB: invoice_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: malbarroso
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    networks:
      - invoice_network

  # Redis for session storage
  redis:
    image: redis:7-alpine
    container_name: invoice_portal_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - invoice_network
    command: redis-server --appendonly yes

  # Backend API (Optional - for production)
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: invoice_portal_backend
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     NODE_ENV: development
  #     DATABASE_URL: postgresql://postgres:password123@postgres:5432/invoice_portal
  #     REDIS_URL: redis://redis:6379
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - invoice_network
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules

volumes:
  postgres_data:
  redis_data:

networks:
  invoice_network:
    driver: bridge
